import { Analyzer } from "@keyandbpm/core";
import { loadEssentiaWasm } from "@keyandbpm/core/node";
import { decodeToMono } from "/Users/mikefarina/development/keyandbpm/apps/cli/src/decode.ts";
const t0 = performance.now();
const pcm = decodeToMono(process.argv[2]!);
const t1 = performance.now();
const a = new Analyzer(loadEssentiaWasm());
const t2 = performance.now();
const marks: string[] = [];
a.analyze(pcm, { onProgress: (u) => marks.push(`${u.type}${u.type === "tempo" ? ":" + u.tempo.method : ""} @${Math.round(performance.now() - t2)}ms`) });
console.log(`length ${(pcm.length / 44100).toFixed(0)}s, decode ${Math.round(t1 - t0)}ms, wasm ${Math.round(t2 - t1)}ms`);
console.log(marks.join("\n"));
